spring:
  application:
    name: auth-server
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitness-tracker}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile

server:
  port: 9090
  forward-headers-strategy: framework

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}

jwt:
  access_secret: ${JWT_ACCESS_SECRET}
  access_duration: ${JWT_ACCESS_DURATION:600000}
  issuer: fitness-tracker-auth-server

refresh_token_duration: ${REFRESH_TOKEN_DURATION:3600000}